services:
  Podzamenu_user.login_listener:
    class: Podzamenu\MainBundle\Listener\LoginListener
    arguments: [@doctrine]
    tags:
      - { name: kernel.event_listener, event: security.interactive_login, method: onLogin }
